name: Build Wheels and AppImage

on:
  push:
  pull_request:
  release:
    types:
      - created


jobs:
  build-appimage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make curl
          python3 -m pip install python-appimage

      - name: Build wheels using Docker
        run: |
          make wheels.tgz

      - name: Upload TGZ file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels.tgz
          path: wheels.tgz

      - name: Build the AppImage
        run: |
          make all

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pptx2md-2.0.6-x86_64.AppImage
          path: ./pptx2md-2.0.6-x86_64.AppImage
          if-no-files-found: error

      - name: Create draft release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Version ${{ github.ref_name }}"
          draft: true
          files: |
            pptx2md-2.0.6-x86_64.AppImage
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


